### PR TITLE
Type checking: Do all the things!

### PR DESCRIPTION
**Pull request by harens**
This PR implements the following:

- Add [beartype](https://github.com/beartype/beartype) and [mypy](https://github.com/python/mypy) as runtime and dev dependencies respectively.
- Make sentipy [PEP 561](https://www.python.org/dev/peps/pep-0561/) compliant.
- Reduced the number of `mypy --strict` errors from ~46 to 0.
- Added a GitHub Action to run `mypy --strict` so as to test this.

This should hopefully be everything you will ever need in terms of adding a type checking foundation.

### CODE REVIEW

**Review by zeevox — COMMENTED** [review]
Is it necessary to annotate each function with `@beartype`? Is there a way of more concisely adding `beartype` everywhere automagically?

**Comment by harens** [comment]
Thanks for reviewing @ZeevoX.

> Is it necessary to annotate each function with @beartype? Is there a way of more concisely adding beartype everywhere automagically?

I assume so since it's just a decorator. However, there are certainly [hacky ways of doing this](https://stackoverflow.com/questions/6307761/how-to-decorate-all-functions-of-a-class-without-typing-it-over-and-over-for-eac) if required.

CC @leycec if he has any better ideas.

**Comment by leycec** [comment]
**Wow.** As the only non-quant in the room, I can only comment that [Sentiment Investor](https://sentimentinvestor.com) looks like pure hotness. Quantifying stock hype via NLP-style metrics on the social media sphere is, indeed, the 4D chess move.

You unsurprisingly ask the hard-hitting questions, @ZeevoX...

> Is it necessary to annotate each function with `@beartype`? Is there a way of more concisely adding `beartype` everywhere automagically?

The short answer to the first question is: "Currently, yes. I'm admittedly lazy, it's *really* hot in Canada, and you're the first potential end user to justifiably want this. I now feel bad we don't provide this. I fully understand if this is a deal-breaker for you."

The long answer to the second question is: "I'm so glad you asked! Since you'd like this, I'd be delighted to help everyone globally decorate everything with `@beartype` without actually needing to do that. On my end, I need to implement a [new AST-based `beartype.beartype_everything()` import hook inspired by typeguard's comparable `typeguard.importhook.install_import_hook()` function](https://github.com/agronholm/typeguard/blob/abcaa5d6f34eaddd4f5cd1ab1c16c853554eaf6c/src/typeguard/importhook.py#L139). That's only 162 lines of pure Python, which means this is mostly trivial, but it's a *dense* 162 lines, which means this might take a week or so. On your end, you might consider waiting for the next stable beartype release and, once released, calling our import hook at the top of your `sentipy.__init__` module to globally and transparently apply `@beartype` across your entire codebase. Does that sound reasonable? If so, it might be useful to defer the `beartype` portion of this PR for just a bit. I'd hate to block SentiPy's mypy compatibility and PEP 561 compliance, which are both indispensable in 2021."

Lastly, thanks to @harens for integrating @beartype into this PR and pinging me up! You are a fundamentally kind soul. :hugs:

**Comment by zeevox** [comment]
Thank you, @leycec, I did not expect such a detailed response! It's certainly not a deal-breaker, so I will approve and merge as-is. I do look forward to a future @beartype release with this functionality, at which point SentiPy can be firmly in the vanguard of using the beartype feature set.

**Review by zeevox — APPROVED** [review]

**Comment by zeevox** [comment]
My thanks to @harens for another superb pull request to sentipy. I should add a contributors hall of fame....

**Comment by harens** [comment]
Thank you very much @ZeevoX for approving and merging this, as well as for maintaining this amazing project!

Also, thanks @leycec for your detailed analysis and kind words. As always, they're greatly appreciated. :)

**Comment by leycec** [comment]
Thanks so much for accepting this as is, @ZeevoX. If @harens isn't relieved, I'll eat my sweaty Tilley hat.

>  I do look forward to a future @beartype release with this functionality, at which point SentiPy can be firmly in the vanguard of using the beartype feature set.

What SentiPy wants, SentiPy gets. I've added a [beartype feature request tracking an automagic import hook extensively quoting you](https://github.com/beartype/beartype/issues/43). Let's see if I do something tomorrow other than gobble fresh raspberries while reading [Brandon Sanderson power fantasies](https://www.goodreads.com/book/show/7235533-the-way-of-kings). :strawberry: :book: 

> Also, thanks @leycec for your detailed analysis and kind words.

You're going places, @harens – places with lots of money! So, not Canada. Seriously, though: thanks for doing all of the heavy lifting here. I didn't even know this exciting NLP thing existed. Now I do and my Wednesday is better for it.

**Pull request merged**
